// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module chirp_chirp_Pipeline_VITIS_LOOP_17_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fs,
        f0,
        mul3,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        grp_fu_77_p_din0,
        grp_fu_77_p_din1,
        grp_fu_77_p_opcode,
        grp_fu_77_p_dout0,
        grp_fu_77_p_ce,
        grp_fu_83_p_din0,
        grp_fu_83_p_din1,
        grp_fu_83_p_dout0,
        grp_fu_83_p_ce,
        grp_fu_88_p_din0,
        grp_fu_88_p_din1,
        grp_fu_88_p_dout0,
        grp_fu_88_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] fs;
input  [31:0] f0;
input  [31:0] mul3;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
output  [31:0] grp_fu_77_p_din0;
output  [31:0] grp_fu_77_p_din1;
output  [0:0] grp_fu_77_p_opcode;
input  [31:0] grp_fu_77_p_dout0;
output   grp_fu_77_p_ce;
output  [31:0] grp_fu_83_p_din0;
output  [31:0] grp_fu_83_p_din1;
input  [31:0] grp_fu_83_p_dout0;
output   grp_fu_83_p_ce;
output  [31:0] grp_fu_88_p_din0;
output  [31:0] grp_fu_88_p_din1;
input  [31:0] grp_fu_88_p_dout0;
output   grp_fu_88_p_ce;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg    ap_enable_reg_pp0_iter45;
reg    ap_enable_reg_pp0_iter46;
reg    ap_enable_reg_pp0_iter47;
reg    ap_enable_reg_pp0_iter48;
reg    ap_enable_reg_pp0_iter49;
reg    ap_enable_reg_pp0_iter50;
reg    ap_enable_reg_pp0_iter51;
reg    ap_enable_reg_pp0_iter52;
reg    ap_enable_reg_pp0_iter53;
reg    ap_enable_reg_pp0_iter54;
reg    ap_enable_reg_pp0_iter55;
reg    ap_enable_reg_pp0_iter56;
reg    ap_enable_reg_pp0_iter57;
reg    ap_enable_reg_pp0_iter58;
reg    ap_enable_reg_pp0_iter59;
reg    ap_enable_reg_pp0_iter60;
reg    ap_enable_reg_pp0_iter61;
reg    ap_enable_reg_pp0_iter62;
reg    ap_enable_reg_pp0_iter63;
reg    ap_enable_reg_pp0_iter64;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln17_fu_401_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [3:0] ref_4oPi_table_100_address0;
wire   [99:0] ref_4oPi_table_100_q0;
wire   [7:0] second_order_float_sin_cos_K0_address0;
wire   [29:0] second_order_float_sin_cos_K0_q0;
wire   [7:0] second_order_float_sin_cos_K1_address0;
wire   [22:0] second_order_float_sin_cos_K1_q0;
wire   [7:0] second_order_float_sin_cos_K2_address0;
wire   [14:0] second_order_float_sin_cos_K2_q0;
wire    ap_block_pp0_stage0_11001;
reg   [9:0] n_1_reg_1314;
reg   [9:0] n_1_reg_1314_pp0_iter1_reg;
reg   [9:0] n_1_reg_1314_pp0_iter2_reg;
reg   [9:0] n_1_reg_1314_pp0_iter3_reg;
reg   [9:0] n_1_reg_1314_pp0_iter4_reg;
reg   [9:0] n_1_reg_1314_pp0_iter5_reg;
reg   [9:0] n_1_reg_1314_pp0_iter6_reg;
reg   [9:0] n_1_reg_1314_pp0_iter7_reg;
reg   [9:0] n_1_reg_1314_pp0_iter8_reg;
reg   [9:0] n_1_reg_1314_pp0_iter9_reg;
reg   [9:0] n_1_reg_1314_pp0_iter10_reg;
reg   [9:0] n_1_reg_1314_pp0_iter11_reg;
reg   [9:0] n_1_reg_1314_pp0_iter12_reg;
reg   [9:0] n_1_reg_1314_pp0_iter13_reg;
reg   [9:0] n_1_reg_1314_pp0_iter14_reg;
reg   [9:0] n_1_reg_1314_pp0_iter15_reg;
reg   [9:0] n_1_reg_1314_pp0_iter16_reg;
reg   [9:0] n_1_reg_1314_pp0_iter17_reg;
reg   [9:0] n_1_reg_1314_pp0_iter18_reg;
reg   [9:0] n_1_reg_1314_pp0_iter19_reg;
reg   [9:0] n_1_reg_1314_pp0_iter20_reg;
reg   [9:0] n_1_reg_1314_pp0_iter21_reg;
reg   [9:0] n_1_reg_1314_pp0_iter22_reg;
reg   [9:0] n_1_reg_1314_pp0_iter23_reg;
reg   [9:0] n_1_reg_1314_pp0_iter24_reg;
reg   [9:0] n_1_reg_1314_pp0_iter25_reg;
reg   [9:0] n_1_reg_1314_pp0_iter26_reg;
reg   [9:0] n_1_reg_1314_pp0_iter27_reg;
reg   [9:0] n_1_reg_1314_pp0_iter28_reg;
reg   [9:0] n_1_reg_1314_pp0_iter29_reg;
reg   [9:0] n_1_reg_1314_pp0_iter30_reg;
reg   [9:0] n_1_reg_1314_pp0_iter31_reg;
reg   [9:0] n_1_reg_1314_pp0_iter32_reg;
reg   [9:0] n_1_reg_1314_pp0_iter33_reg;
reg   [9:0] n_1_reg_1314_pp0_iter34_reg;
reg   [9:0] n_1_reg_1314_pp0_iter35_reg;
reg   [9:0] n_1_reg_1314_pp0_iter36_reg;
reg   [9:0] n_1_reg_1314_pp0_iter37_reg;
reg   [9:0] n_1_reg_1314_pp0_iter38_reg;
reg   [9:0] n_1_reg_1314_pp0_iter39_reg;
reg   [9:0] n_1_reg_1314_pp0_iter40_reg;
reg   [9:0] n_1_reg_1314_pp0_iter41_reg;
reg   [9:0] n_1_reg_1314_pp0_iter42_reg;
reg   [9:0] n_1_reg_1314_pp0_iter43_reg;
reg   [9:0] n_1_reg_1314_pp0_iter44_reg;
reg   [9:0] n_1_reg_1314_pp0_iter45_reg;
reg   [9:0] n_1_reg_1314_pp0_iter46_reg;
reg   [9:0] n_1_reg_1314_pp0_iter47_reg;
reg   [9:0] n_1_reg_1314_pp0_iter48_reg;
reg   [9:0] n_1_reg_1314_pp0_iter49_reg;
reg   [9:0] n_1_reg_1314_pp0_iter50_reg;
reg   [9:0] n_1_reg_1314_pp0_iter51_reg;
reg   [9:0] n_1_reg_1314_pp0_iter52_reg;
reg   [9:0] n_1_reg_1314_pp0_iter53_reg;
reg   [9:0] n_1_reg_1314_pp0_iter54_reg;
reg   [9:0] n_1_reg_1314_pp0_iter55_reg;
reg   [9:0] n_1_reg_1314_pp0_iter56_reg;
reg   [9:0] n_1_reg_1314_pp0_iter57_reg;
reg   [9:0] n_1_reg_1314_pp0_iter58_reg;
reg   [9:0] n_1_reg_1314_pp0_iter59_reg;
reg   [9:0] n_1_reg_1314_pp0_iter60_reg;
reg   [9:0] n_1_reg_1314_pp0_iter61_reg;
reg   [9:0] n_1_reg_1314_pp0_iter62_reg;
reg   [9:0] n_1_reg_1314_pp0_iter63_reg;
wire   [31:0] grp_fu_361_p1;
reg   [31:0] conv_reg_1329;
reg   [31:0] t_reg_1334;
reg   [31:0] t_reg_1334_pp0_iter23_reg;
reg   [31:0] t_reg_1334_pp0_iter24_reg;
reg   [31:0] t_reg_1334_pp0_iter25_reg;
reg   [31:0] t_reg_1334_pp0_iter26_reg;
reg   [31:0] mul4_reg_1341;
wire   [31:0] grp_fu_349_p2;
reg   [31:0] mul_reg_1346;
wire   [31:0] grp_fu_353_p2;
reg   [31:0] mul5_reg_1351;
reg   [31:0] add_reg_1356;
wire   [63:0] grp_fu_367_p1;
reg   [63:0] conv6_reg_1361;
wire   [63:0] grp_fu_370_p2;
reg   [63:0] mul7_reg_1366;
wire   [31:0] grp_fu_364_p1;
reg   [31:0] phase_reg_1371;
reg   [0:0] din_sign_reg_1376;
reg   [0:0] din_sign_reg_1376_pp0_iter48_reg;
reg   [0:0] din_sign_reg_1376_pp0_iter49_reg;
reg   [0:0] din_sign_reg_1376_pp0_iter50_reg;
reg   [0:0] din_sign_reg_1376_pp0_iter51_reg;
reg   [0:0] din_sign_reg_1376_pp0_iter52_reg;
reg   [0:0] din_sign_reg_1376_pp0_iter53_reg;
wire   [7:0] din_exp_fu_427_p3;
reg   [7:0] din_exp_reg_1381;
reg   [7:0] din_exp_reg_1381_pp0_iter48_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter49_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter50_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter51_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter52_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter53_reg;
reg   [7:0] din_exp_reg_1381_pp0_iter54_reg;
wire   [22:0] din_sig_fu_435_p1;
reg   [22:0] din_sig_reg_1388;
reg   [22:0] din_sig_reg_1388_pp0_iter48_reg;
wire   [0:0] closepath_fu_439_p2;
reg   [0:0] closepath_reg_1394;
reg   [0:0] closepath_reg_1394_pp0_iter48_reg;
reg   [0:0] closepath_reg_1394_pp0_iter49_reg;
reg   [0:0] closepath_reg_1394_pp0_iter50_reg;
reg   [0:0] closepath_reg_1394_pp0_iter51_reg;
reg   [0:0] closepath_reg_1394_pp0_iter52_reg;
reg   [0:0] closepath_reg_1394_pp0_iter53_reg;
reg   [0:0] closepath_reg_1394_pp0_iter54_reg;
wire   [3:0] trunc_ln379_fu_474_p1;
reg   [3:0] trunc_ln379_reg_1405;
reg  signed [79:0] Med_reg_1410;
wire   [0:0] and_ln271_fu_517_p2;
reg   [0:0] and_ln271_reg_1420;
reg   [0:0] and_ln271_reg_1420_pp0_iter50_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter51_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter52_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter53_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter54_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter55_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter56_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter57_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter58_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter59_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter60_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter61_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter62_reg;
reg   [0:0] and_ln271_reg_1420_pp0_iter63_reg;
reg   [57:0] Mx_bits_reg_1427;
reg   [2:0] trunc_ln_i_reg_1433;
wire   [57:0] Mx_bits_3_fu_558_p3;
reg   [57:0] Mx_bits_3_reg_1438;
reg   [28:0] tmp_7_i_reg_1443;
wire   [0:0] sin_basis_fu_573_p19;
reg   [0:0] sin_basis_reg_1448;
reg   [0:0] sin_basis_reg_1448_pp0_iter55_reg;
reg   [0:0] sin_basis_reg_1448_pp0_iter56_reg;
wire   [0:0] icmp_ln282_fu_772_p2;
reg   [0:0] icmp_ln282_reg_1455;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter55_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter56_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter57_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter58_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter59_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter60_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter61_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter62_reg;
reg   [0:0] icmp_ln282_reg_1455_pp0_iter63_reg;
wire   [0:0] results_sign_2_fu_794_p2;
reg   [0:0] results_sign_2_reg_1462;
reg   [0:0] results_sign_2_reg_1462_pp0_iter55_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter56_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter57_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter58_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter59_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter60_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter61_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter62_reg;
reg   [0:0] results_sign_2_reg_1462_pp0_iter63_reg;
reg   [28:0] Mx_reg_1467;
wire   [7:0] Ex_1_fu_850_p2;
reg   [7:0] Ex_1_reg_1473;
reg   [7:0] Ex_1_reg_1473_pp0_iter56_reg;
reg   [0:0] tmp_reg_1479;
wire   [7:0] sub_ln506_fu_864_p2;
reg   [7:0] sub_ln506_reg_1485;
wire   [21:0] B_fu_901_p1;
reg   [21:0] B_reg_1490;
reg   [21:0] B_reg_1490_pp0_iter57_reg;
reg   [21:0] B_reg_1490_pp0_iter58_reg;
wire   [28:0] Mx_1_fu_905_p3;
reg   [28:0] Mx_1_reg_1495;
reg   [28:0] Mx_1_reg_1495_pp0_iter57_reg;
reg   [28:0] Mx_1_reg_1495_pp0_iter58_reg;
reg   [28:0] Mx_1_reg_1495_pp0_iter59_reg;
reg   [28:0] Mx_1_reg_1495_pp0_iter60_reg;
reg   [6:0] tmp_i_reg_1500;
reg   [14:0] B_trunc_reg_1505;
reg   [14:0] B_trunc_reg_1505_pp0_iter57_reg;
wire   [7:0] Ex_2_fu_931_p3;
reg   [7:0] Ex_2_reg_1510;
reg   [7:0] Ex_2_reg_1510_pp0_iter58_reg;
reg   [7:0] Ex_2_reg_1510_pp0_iter59_reg;
reg   [7:0] Ex_2_reg_1510_pp0_iter60_reg;
reg   [7:0] Ex_2_reg_1510_pp0_iter61_reg;
reg   [7:0] Ex_2_reg_1510_pp0_iter62_reg;
reg   [7:0] Ex_2_reg_1510_pp0_iter63_reg;
reg   [14:0] B_squared_reg_1530;
reg   [28:0] t1_reg_1535;
reg   [28:0] t1_reg_1535_pp0_iter59_reg;
reg  signed [22:0] second_order_float_sin_cos_K1_load_reg_1540;
reg  signed [14:0] second_order_float_sin_cos_K2_load_reg_1545;
reg   [21:0] trunc_ln2_reg_1550;
reg   [13:0] trunc_ln3_reg_1555;
wire   [29:0] add_ln32_1_fu_1034_p2;
reg  signed [29:0] add_ln32_1_reg_1560;
reg   [28:0] result_reg_1575;
reg   [15:0] tmp_1_i_reg_1580;
reg   [12:0] tmp_3_i_reg_1585;
reg   [27:0] trunc_ln5_reg_1590;
wire   [4:0] trunc_ln281_fu_1110_p1;
reg   [4:0] trunc_ln281_reg_1595;
wire   [3:0] trunc_ln281_1_fu_1126_p1;
reg   [3:0] trunc_ln281_1_reg_1600;
wire   [27:0] in_shift_1_fu_1130_p2;
reg   [27:0] in_shift_1_reg_1606;
wire   [0:0] icmp_ln292_fu_1135_p2;
reg   [0:0] icmp_ln292_reg_1612;
wire   [0:0] icmp_ln306_fu_1141_p2;
reg   [0:0] icmp_ln306_reg_1618;
wire   [63:0] zext_ln378_fu_469_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln28_fu_943_p1;
wire   [63:0] zext_ln17_fu_1146_p1;
reg   [9:0] n_fu_254;
wire   [9:0] n_3_fu_395_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_n_1;
reg    ref_4oPi_table_100_ce0_local;
reg    second_order_float_sin_cos_K0_ce0_local;
reg    second_order_float_sin_cos_K1_ce0_local;
reg    second_order_float_sin_cos_K2_ce0_local;
reg    out_r_we0_local;
wire   [31:0] t_3_fu_1282_p4;
reg    out_r_ce0_local;
wire   [31:0] grp_fu_361_p0;
wire   [21:0] mul_ln29_fu_375_p1;
wire   [28:0] grp_fu_379_p1;
wire   [23:0] grp_fu_383_p1;
wire   [31:0] data_fu_416_p1;
wire   [7:0] add_ln376_fu_445_p2;
wire   [7:0] addr_fu_451_p3;
wire   [3:0] lshr_ln_fu_459_p4;
wire   [99:0] zext_ln379_fu_478_p1;
wire   [99:0] shl_ln379_fu_481_p2;
wire   [23:0] X_fu_495_p3;
wire   [0:0] icmp_ln271_fu_507_p2;
wire   [0:0] icmp_ln271_1_fu_512_p2;
wire   [79:0] grp_fu_383_p2;
wire   [2:0] k_fu_543_p3;
wire   [0:0] trunc_ln491_fu_549_p1;
wire   [57:0] Mx_bits_1_fu_553_p2;
wire   [0:0] sin_basis_fu_573_p17;
wire   [0:0] tmp_4_i_fu_620_p33;
wire   [3:0] index_fu_613_p3;
wire   [0:0] tmp_8_i_fu_692_p33;
wire   [0:0] tmp_4_i_fu_620_p35;
wire   [0:0] tmp_8_i_fu_692_p35;
wire   [0:0] results_sign_fu_764_p3;
wire   [0:0] xor_ln282_fu_777_p2;
wire   [0:0] results_sign_1_fu_783_p2;
wire   [0:0] not_and_ln271_i_fu_789_p2;
wire   [7:0] Ex_fu_800_p2;
wire   [29:0] Mx_zeros_fu_819_p1;
wire   [29:0] Mx_zeros_fu_819_p3;
wire   [57:0] zext_ln504_fu_827_p1;
wire   [57:0] shl_ln504_fu_831_p2;
wire   [7:0] select_ln453_fu_805_p3;
wire   [7:0] trunc_ln505_fu_846_p1;
wire   [7:0] select_ln506_fu_870_p3;
wire   [31:0] zext_ln506_1_fu_879_p1;
wire   [31:0] zext_ln506_fu_875_p1;
wire   [31:0] lshr_ln506_fu_882_p2;
wire   [31:0] shl_ln506_fu_888_p2;
wire   [31:0] select_ln506_1_fu_894_p3;
wire   [7:0] A_fu_937_p3;
wire   [14:0] mul_ln23_fu_953_p0;
wire   [29:0] zext_ln23_fu_950_p1;
wire   [14:0] mul_ln23_fu_953_p1;
wire   [29:0] mul_ln23_fu_953_p2;
wire   [44:0] mul_ln29_fu_375_p2;
wire   [14:0] mul_ln30_fu_1003_p0;
wire   [29:0] mul_ln30_fu_1003_p2;
wire  signed [29:0] sext_ln32_fu_1019_p1;
wire  signed [29:0] sext_ln32_1_fu_1022_p1;
wire   [29:0] add_ln32_fu_1025_p2;
wire  signed [29:0] sext_ln32_2_fu_1031_p1;
wire   [57:0] grp_fu_379_p2;
wire   [31:0] c_fu_1102_p1;
wire   [31:0] c_fu_1102_p3;
wire   [31:0] c_1_fu_1118_p1;
wire   [31:0] c_1_fu_1118_p3;
wire   [27:0] zext_ln281_fu_1114_p1;
wire   [27:0] zext_ln281_1_fu_1153_p1;
wire   [4:0] shift_1_fu_1156_p3;
wire   [4:0] shift_2_fu_1168_p3;
wire  signed [8:0] sext_ln252_fu_1150_p1;
wire   [8:0] add_ln300_fu_1178_p2;
wire   [8:0] zext_ln286_fu_1174_p1;
wire   [8:0] newexp_fu_1184_p2;
wire   [0:0] tmp_3_fu_1190_p3;
wire   [27:0] in_shift_2_fu_1163_p2;
wire   [22:0] tmp_1_fu_1207_p4;
wire   [22:0] tmp_2_fu_1217_p4;
wire   [0:0] or_ln306_fu_1198_p2;
wire   [0:0] or_ln282_fu_1240_p2;
wire   [7:0] select_ln282_fu_1233_p3;
wire   [7:0] empty_fu_1203_p1;
wire   [22:0] select_ln282_2_fu_1253_p3;
wire   [22:0] empty_27_fu_1226_p3;
wire   [7:0] results_exp_fu_1245_p3;
wire   [22:0] results_sig_fu_1260_p3;
wire   [7:0] results_exp_1_fu_1268_p3;
wire   [22:0] results_sig_1_fu_1275_p3;
wire    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg    ap_loop_exit_ready_pp0_iter20_reg;
reg    ap_loop_exit_ready_pp0_iter21_reg;
reg    ap_loop_exit_ready_pp0_iter22_reg;
reg    ap_loop_exit_ready_pp0_iter23_reg;
reg    ap_loop_exit_ready_pp0_iter24_reg;
reg    ap_loop_exit_ready_pp0_iter25_reg;
reg    ap_loop_exit_ready_pp0_iter26_reg;
reg    ap_loop_exit_ready_pp0_iter27_reg;
reg    ap_loop_exit_ready_pp0_iter28_reg;
reg    ap_loop_exit_ready_pp0_iter29_reg;
reg    ap_loop_exit_ready_pp0_iter30_reg;
reg    ap_loop_exit_ready_pp0_iter31_reg;
reg    ap_loop_exit_ready_pp0_iter32_reg;
reg    ap_loop_exit_ready_pp0_iter33_reg;
reg    ap_loop_exit_ready_pp0_iter34_reg;
reg    ap_loop_exit_ready_pp0_iter35_reg;
reg    ap_loop_exit_ready_pp0_iter36_reg;
reg    ap_loop_exit_ready_pp0_iter37_reg;
reg    ap_loop_exit_ready_pp0_iter38_reg;
reg    ap_loop_exit_ready_pp0_iter39_reg;
reg    ap_loop_exit_ready_pp0_iter40_reg;
reg    ap_loop_exit_ready_pp0_iter41_reg;
reg    ap_loop_exit_ready_pp0_iter42_reg;
reg    ap_loop_exit_ready_pp0_iter43_reg;
reg    ap_loop_exit_ready_pp0_iter44_reg;
reg    ap_loop_exit_ready_pp0_iter45_reg;
reg    ap_loop_exit_ready_pp0_iter46_reg;
reg    ap_loop_exit_ready_pp0_iter47_reg;
reg    ap_loop_exit_ready_pp0_iter48_reg;
reg    ap_loop_exit_ready_pp0_iter49_reg;
reg    ap_loop_exit_ready_pp0_iter50_reg;
reg    ap_loop_exit_ready_pp0_iter51_reg;
reg    ap_loop_exit_ready_pp0_iter52_reg;
reg    ap_loop_exit_ready_pp0_iter53_reg;
reg    ap_loop_exit_ready_pp0_iter54_reg;
reg    ap_loop_exit_ready_pp0_iter55_reg;
reg    ap_loop_exit_ready_pp0_iter56_reg;
reg    ap_loop_exit_ready_pp0_iter57_reg;
reg    ap_loop_exit_ready_pp0_iter58_reg;
reg    ap_loop_exit_ready_pp0_iter59_reg;
reg    ap_loop_exit_ready_pp0_iter60_reg;
reg    ap_loop_exit_ready_pp0_iter61_reg;
reg    ap_loop_exit_ready_pp0_iter62_reg;
reg    ap_loop_exit_ready_pp0_iter63_reg;
reg    ap_loop_exit_ready_pp0_iter64_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [57:0] grp_fu_379_p10;
wire   [79:0] grp_fu_383_p10;
wire   [44:0] mul_ln29_fu_375_p10;
wire   [29:0] mul_ln30_fu_1003_p00;
wire   [2:0] sin_basis_fu_573_p1;
wire   [2:0] sin_basis_fu_573_p3;
wire   [2:0] sin_basis_fu_573_p5;
wire   [2:0] sin_basis_fu_573_p7;
wire  signed [2:0] sin_basis_fu_573_p9;
wire  signed [2:0] sin_basis_fu_573_p11;
wire  signed [2:0] sin_basis_fu_573_p13;
wire  signed [2:0] sin_basis_fu_573_p15;
wire   [3:0] tmp_4_i_fu_620_p1;
wire   [3:0] tmp_4_i_fu_620_p3;
wire   [3:0] tmp_4_i_fu_620_p5;
wire   [3:0] tmp_4_i_fu_620_p7;
wire   [3:0] tmp_4_i_fu_620_p9;
wire   [3:0] tmp_4_i_fu_620_p11;
wire   [3:0] tmp_4_i_fu_620_p13;
wire   [3:0] tmp_4_i_fu_620_p15;
wire  signed [3:0] tmp_4_i_fu_620_p17;
wire  signed [3:0] tmp_4_i_fu_620_p19;
wire  signed [3:0] tmp_4_i_fu_620_p21;
wire  signed [3:0] tmp_4_i_fu_620_p23;
wire  signed [3:0] tmp_4_i_fu_620_p25;
wire  signed [3:0] tmp_4_i_fu_620_p27;
wire  signed [3:0] tmp_4_i_fu_620_p29;
wire  signed [3:0] tmp_4_i_fu_620_p31;
wire   [3:0] tmp_8_i_fu_692_p1;
wire   [3:0] tmp_8_i_fu_692_p3;
wire   [3:0] tmp_8_i_fu_692_p5;
wire   [3:0] tmp_8_i_fu_692_p7;
wire   [3:0] tmp_8_i_fu_692_p9;
wire   [3:0] tmp_8_i_fu_692_p11;
wire   [3:0] tmp_8_i_fu_692_p13;
wire   [3:0] tmp_8_i_fu_692_p15;
wire  signed [3:0] tmp_8_i_fu_692_p17;
wire  signed [3:0] tmp_8_i_fu_692_p19;
wire  signed [3:0] tmp_8_i_fu_692_p21;
wire  signed [3:0] tmp_8_i_fu_692_p23;
wire  signed [3:0] tmp_8_i_fu_692_p25;
wire  signed [3:0] tmp_8_i_fu_692_p27;
wire  signed [3:0] tmp_8_i_fu_692_p29;
wire  signed [3:0] tmp_8_i_fu_692_p31;
wire   [29:0] Mx_zeros_fu_819_p0;
wire   [0:0] Mx_zeros_fu_819_p2;
wire   [31:0] c_fu_1102_p0;
wire   [0:0] c_fu_1102_p2;
wire   [31:0] c_1_fu_1118_p0;
wire   [0:0] c_1_fu_1118_p2;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
#0 ap_enable_reg_pp0_iter45 = 1'b0;
#0 ap_enable_reg_pp0_iter46 = 1'b0;
#0 ap_enable_reg_pp0_iter47 = 1'b0;
#0 ap_enable_reg_pp0_iter48 = 1'b0;
#0 ap_enable_reg_pp0_iter49 = 1'b0;
#0 ap_enable_reg_pp0_iter50 = 1'b0;
#0 ap_enable_reg_pp0_iter51 = 1'b0;
#0 ap_enable_reg_pp0_iter52 = 1'b0;
#0 ap_enable_reg_pp0_iter53 = 1'b0;
#0 ap_enable_reg_pp0_iter54 = 1'b0;
#0 ap_enable_reg_pp0_iter55 = 1'b0;
#0 ap_enable_reg_pp0_iter56 = 1'b0;
#0 ap_enable_reg_pp0_iter57 = 1'b0;
#0 ap_enable_reg_pp0_iter58 = 1'b0;
#0 ap_enable_reg_pp0_iter59 = 1'b0;
#0 ap_enable_reg_pp0_iter60 = 1'b0;
#0 ap_enable_reg_pp0_iter61 = 1'b0;
#0 ap_enable_reg_pp0_iter62 = 1'b0;
#0 ap_enable_reg_pp0_iter63 = 1'b0;
#0 ap_enable_reg_pp0_iter64 = 1'b0;
#0 n_fu_254 = 10'd0;
#0 ap_done_reg = 1'b0;
end

chirp_chirp_Pipeline_VITIS_LOOP_17_1_ref_4oPi_table_100_ROM_1P_LUTRAM_1R #(
    .DataWidth( 100 ),
    .AddressRange( 13 ),
    .AddressWidth( 4 ))
ref_4oPi_table_100_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(ref_4oPi_table_100_address0),
    .ce0(ref_4oPi_table_100_ce0_local),
    .q0(ref_4oPi_table_100_q0)
);

chirp_chirp_Pipeline_VITIS_LOOP_17_1_second_order_float_sin_cos_K0_ROM_1P_LUTRAM_1R #(
    .DataWidth( 30 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K0_address0),
    .ce0(second_order_float_sin_cos_K0_ce0_local),
    .q0(second_order_float_sin_cos_K0_q0)
);

chirp_chirp_Pipeline_VITIS_LOOP_17_1_second_order_float_sin_cos_K1_ROM_1P_LUTRAM_1R #(
    .DataWidth( 23 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K1_address0),
    .ce0(second_order_float_sin_cos_K1_ce0_local),
    .q0(second_order_float_sin_cos_K1_q0)
);

chirp_chirp_Pipeline_VITIS_LOOP_17_1_second_order_float_sin_cos_K2_ROM_1P_LUTRAM_1R #(
    .DataWidth( 15 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
second_order_float_sin_cos_K2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(second_order_float_sin_cos_K2_address0),
    .ce0(second_order_float_sin_cos_K2_ce0_local),
    .q0(second_order_float_sin_cos_K2_q0)
);

chirp_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(t_reg_1334_pp0_iter26_reg),
    .din1(f0),
    .ce(1'b1),
    .dout(grp_fu_349_p2)
);

chirp_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul4_reg_1341),
    .din1(t_reg_1334_pp0_iter26_reg),
    .ce(1'b1),
    .dout(grp_fu_353_p2)
);

chirp_sitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sitofp_32ns_32_6_no_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_361_p0),
    .ce(1'b1),
    .dout(grp_fu_361_p1)
);

chirp_fptrunc_64ns_32_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 64 ),
    .dout_WIDTH( 32 ))
fptrunc_64ns_32_2_no_dsp_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul7_reg_1366),
    .ce(1'b1),
    .dout(grp_fu_364_p1)
);

chirp_fpext_32ns_64_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
fpext_32ns_64_2_no_dsp_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_reg_1356),
    .ce(1'b1),
    .dout(grp_fu_367_p1)
);

chirp_dmul_64ns_64ns_64_7_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 64 ))
dmul_64ns_64ns_64_7_max_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(conv6_reg_1361),
    .din1(64'd4618760256179416344),
    .ce(1'b1),
    .dout(grp_fu_370_p2)
);

chirp_mul_23s_22ns_45_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 23 ),
    .din1_WIDTH( 22 ),
    .dout_WIDTH( 45 ))
mul_23s_22ns_45_1_1_U10(
    .din0(second_order_float_sin_cos_K1_load_reg_1540),
    .din1(mul_ln29_fu_375_p1),
    .dout(mul_ln29_fu_375_p2)
);

chirp_mul_30s_29ns_58_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 30 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 58 ))
mul_30s_29ns_58_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln32_1_reg_1560),
    .din1(grp_fu_379_p1),
    .ce(1'b1),
    .dout(grp_fu_379_p2)
);

chirp_mul_80s_24ns_80_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 80 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 80 ))
mul_80s_24ns_80_5_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(Med_reg_1410),
    .din1(grp_fu_383_p1),
    .ce(1'b1),
    .dout(grp_fu_383_p2)
);

(* dissolve_hierarchy = "yes" *) chirp_sparsemux_17_3_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 1 ))
sparsemux_17_3_1_1_1_U13(
    .din0(1'd0),
    .din1(1'd1),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd0),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .def(sin_basis_fu_573_p17),
    .sel(k_fu_543_p3),
    .dout(sin_basis_fu_573_p19)
);

(* dissolve_hierarchy = "yes" *) chirp_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U14(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd1),
    .din3(1'd0),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd0),
    .din7(1'd1),
    .din8(1'd1),
    .din9(1'd0),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd0),
    .din13(1'd1),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_4_i_fu_620_p33),
    .sel(index_fu_613_p3),
    .dout(tmp_4_i_fu_620_p35)
);

(* dissolve_hierarchy = "yes" *) chirp_sparsemux_33_4_1_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 1 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 1 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 1 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 1 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 1 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 1 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 1 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 1 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 1 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 1 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 1 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 1 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 1 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 1 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 1 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 1 ),
    .def_WIDTH( 1 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
sparsemux_33_4_1_1_1_U15(
    .din0(1'd0),
    .din1(1'd0),
    .din2(1'd0),
    .din3(1'd1),
    .din4(1'd1),
    .din5(1'd1),
    .din6(1'd1),
    .din7(1'd0),
    .din8(1'd0),
    .din9(1'd1),
    .din10(1'd1),
    .din11(1'd1),
    .din12(1'd1),
    .din13(1'd0),
    .din14(1'd0),
    .din15(1'd0),
    .def(tmp_8_i_fu_692_p33),
    .sel(index_fu_613_p3),
    .dout(tmp_8_i_fu_692_p35)
);

chirp_ctlz_30_30_1_1 #(
    .din_WIDTH( 30 ),
    .dout_WIDTH( 30 ))
ctlz_30_30_1_1_U16(
    .din(Mx_zeros_fu_819_p1),
    .dout(Mx_zeros_fu_819_p3)
);

chirp_mul_15ns_15ns_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15ns_30_1_1_U17(
    .din0(mul_ln23_fu_953_p0),
    .din1(mul_ln23_fu_953_p1),
    .dout(mul_ln23_fu_953_p2)
);

chirp_mul_15ns_15s_30_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 15 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 30 ))
mul_15ns_15s_30_1_1_U18(
    .din0(mul_ln30_fu_1003_p0),
    .din1(second_order_float_sin_cos_K2_load_reg_1545),
    .dout(mul_ln30_fu_1003_p2)
);

chirp_ctlz_32_32_1_1 #(
    .din_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ctlz_32_32_1_1_U19(
    .din(c_fu_1102_p1),
    .dout(c_fu_1102_p3)
);

chirp_ctlz_32_32_1_1 #(
    .din_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
ctlz_32_32_1_1_U20(
    .din(c_1_fu_1118_p1),
    .dout(c_1_fu_1118_p3)
);

chirp_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter64_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter45 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter45 <= ap_enable_reg_pp0_iter44;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter46 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter46 <= ap_enable_reg_pp0_iter45;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter47 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter47 <= ap_enable_reg_pp0_iter46;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter48 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter48 <= ap_enable_reg_pp0_iter47;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter49 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter49 <= ap_enable_reg_pp0_iter48;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter50 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter50 <= ap_enable_reg_pp0_iter49;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter51 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter51 <= ap_enable_reg_pp0_iter50;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter52 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter52 <= ap_enable_reg_pp0_iter51;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter53 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter53 <= ap_enable_reg_pp0_iter52;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter54 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter54 <= ap_enable_reg_pp0_iter53;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter55 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter55 <= ap_enable_reg_pp0_iter54;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter56 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter56 <= ap_enable_reg_pp0_iter55;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter57 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter57 <= ap_enable_reg_pp0_iter56;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter58 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter58 <= ap_enable_reg_pp0_iter57;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter59 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter59 <= ap_enable_reg_pp0_iter58;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter60 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter60 <= ap_enable_reg_pp0_iter59;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter61 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter61 <= ap_enable_reg_pp0_iter60;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter62 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter62 <= ap_enable_reg_pp0_iter61;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter63 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter63 <= ap_enable_reg_pp0_iter62;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter64 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter64 <= ap_enable_reg_pp0_iter63;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter63_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter64_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter64_reg <= ap_loop_exit_ready_pp0_iter63_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
            n_fu_254 <= n_3_fu_395_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            n_fu_254 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        B_reg_1490 <= B_fu_901_p1;
        B_reg_1490_pp0_iter57_reg <= B_reg_1490;
        B_reg_1490_pp0_iter58_reg <= B_reg_1490_pp0_iter57_reg;
        B_squared_reg_1530 <= {{mul_ln23_fu_953_p2[29:15]}};
        B_trunc_reg_1505 <= {{select_ln506_1_fu_894_p3[21:7]}};
        B_trunc_reg_1505_pp0_iter57_reg <= B_trunc_reg_1505;
        Ex_1_reg_1473 <= Ex_1_fu_850_p2;
        Ex_1_reg_1473_pp0_iter56_reg <= Ex_1_reg_1473;
        Ex_2_reg_1510 <= Ex_2_fu_931_p3;
        Ex_2_reg_1510_pp0_iter58_reg <= Ex_2_reg_1510;
        Ex_2_reg_1510_pp0_iter59_reg <= Ex_2_reg_1510_pp0_iter58_reg;
        Ex_2_reg_1510_pp0_iter60_reg <= Ex_2_reg_1510_pp0_iter59_reg;
        Ex_2_reg_1510_pp0_iter61_reg <= Ex_2_reg_1510_pp0_iter60_reg;
        Ex_2_reg_1510_pp0_iter62_reg <= Ex_2_reg_1510_pp0_iter61_reg;
        Ex_2_reg_1510_pp0_iter63_reg <= Ex_2_reg_1510_pp0_iter62_reg;
        Med_reg_1410 <= {{shl_ln379_fu_481_p2[99:20]}};
        Mx_1_reg_1495 <= Mx_1_fu_905_p3;
        Mx_1_reg_1495_pp0_iter57_reg <= Mx_1_reg_1495;
        Mx_1_reg_1495_pp0_iter58_reg <= Mx_1_reg_1495_pp0_iter57_reg;
        Mx_1_reg_1495_pp0_iter59_reg <= Mx_1_reg_1495_pp0_iter58_reg;
        Mx_1_reg_1495_pp0_iter60_reg <= Mx_1_reg_1495_pp0_iter59_reg;
        Mx_bits_3_reg_1438 <= Mx_bits_3_fu_558_p3;
        Mx_bits_reg_1427 <= {{grp_fu_383_p2[76:19]}};
        Mx_reg_1467 <= {{shl_ln504_fu_831_p2[57:29]}};
        add_ln32_1_reg_1560 <= add_ln32_1_fu_1034_p2;
        add_reg_1356 <= grp_fu_77_p_dout0;
        and_ln271_reg_1420 <= and_ln271_fu_517_p2;
        and_ln271_reg_1420_pp0_iter50_reg <= and_ln271_reg_1420;
        and_ln271_reg_1420_pp0_iter51_reg <= and_ln271_reg_1420_pp0_iter50_reg;
        and_ln271_reg_1420_pp0_iter52_reg <= and_ln271_reg_1420_pp0_iter51_reg;
        and_ln271_reg_1420_pp0_iter53_reg <= and_ln271_reg_1420_pp0_iter52_reg;
        and_ln271_reg_1420_pp0_iter54_reg <= and_ln271_reg_1420_pp0_iter53_reg;
        and_ln271_reg_1420_pp0_iter55_reg <= and_ln271_reg_1420_pp0_iter54_reg;
        and_ln271_reg_1420_pp0_iter56_reg <= and_ln271_reg_1420_pp0_iter55_reg;
        and_ln271_reg_1420_pp0_iter57_reg <= and_ln271_reg_1420_pp0_iter56_reg;
        and_ln271_reg_1420_pp0_iter58_reg <= and_ln271_reg_1420_pp0_iter57_reg;
        and_ln271_reg_1420_pp0_iter59_reg <= and_ln271_reg_1420_pp0_iter58_reg;
        and_ln271_reg_1420_pp0_iter60_reg <= and_ln271_reg_1420_pp0_iter59_reg;
        and_ln271_reg_1420_pp0_iter61_reg <= and_ln271_reg_1420_pp0_iter60_reg;
        and_ln271_reg_1420_pp0_iter62_reg <= and_ln271_reg_1420_pp0_iter61_reg;
        and_ln271_reg_1420_pp0_iter63_reg <= and_ln271_reg_1420_pp0_iter62_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
        ap_loop_exit_ready_pp0_iter20_reg <= ap_loop_exit_ready_pp0_iter19_reg;
        ap_loop_exit_ready_pp0_iter21_reg <= ap_loop_exit_ready_pp0_iter20_reg;
        ap_loop_exit_ready_pp0_iter22_reg <= ap_loop_exit_ready_pp0_iter21_reg;
        ap_loop_exit_ready_pp0_iter23_reg <= ap_loop_exit_ready_pp0_iter22_reg;
        ap_loop_exit_ready_pp0_iter24_reg <= ap_loop_exit_ready_pp0_iter23_reg;
        ap_loop_exit_ready_pp0_iter25_reg <= ap_loop_exit_ready_pp0_iter24_reg;
        ap_loop_exit_ready_pp0_iter26_reg <= ap_loop_exit_ready_pp0_iter25_reg;
        ap_loop_exit_ready_pp0_iter27_reg <= ap_loop_exit_ready_pp0_iter26_reg;
        ap_loop_exit_ready_pp0_iter28_reg <= ap_loop_exit_ready_pp0_iter27_reg;
        ap_loop_exit_ready_pp0_iter29_reg <= ap_loop_exit_ready_pp0_iter28_reg;
        ap_loop_exit_ready_pp0_iter30_reg <= ap_loop_exit_ready_pp0_iter29_reg;
        ap_loop_exit_ready_pp0_iter31_reg <= ap_loop_exit_ready_pp0_iter30_reg;
        ap_loop_exit_ready_pp0_iter32_reg <= ap_loop_exit_ready_pp0_iter31_reg;
        ap_loop_exit_ready_pp0_iter33_reg <= ap_loop_exit_ready_pp0_iter32_reg;
        ap_loop_exit_ready_pp0_iter34_reg <= ap_loop_exit_ready_pp0_iter33_reg;
        ap_loop_exit_ready_pp0_iter35_reg <= ap_loop_exit_ready_pp0_iter34_reg;
        ap_loop_exit_ready_pp0_iter36_reg <= ap_loop_exit_ready_pp0_iter35_reg;
        ap_loop_exit_ready_pp0_iter37_reg <= ap_loop_exit_ready_pp0_iter36_reg;
        ap_loop_exit_ready_pp0_iter38_reg <= ap_loop_exit_ready_pp0_iter37_reg;
        ap_loop_exit_ready_pp0_iter39_reg <= ap_loop_exit_ready_pp0_iter38_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter40_reg <= ap_loop_exit_ready_pp0_iter39_reg;
        ap_loop_exit_ready_pp0_iter41_reg <= ap_loop_exit_ready_pp0_iter40_reg;
        ap_loop_exit_ready_pp0_iter42_reg <= ap_loop_exit_ready_pp0_iter41_reg;
        ap_loop_exit_ready_pp0_iter43_reg <= ap_loop_exit_ready_pp0_iter42_reg;
        ap_loop_exit_ready_pp0_iter44_reg <= ap_loop_exit_ready_pp0_iter43_reg;
        ap_loop_exit_ready_pp0_iter45_reg <= ap_loop_exit_ready_pp0_iter44_reg;
        ap_loop_exit_ready_pp0_iter46_reg <= ap_loop_exit_ready_pp0_iter45_reg;
        ap_loop_exit_ready_pp0_iter47_reg <= ap_loop_exit_ready_pp0_iter46_reg;
        ap_loop_exit_ready_pp0_iter48_reg <= ap_loop_exit_ready_pp0_iter47_reg;
        ap_loop_exit_ready_pp0_iter49_reg <= ap_loop_exit_ready_pp0_iter48_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter50_reg <= ap_loop_exit_ready_pp0_iter49_reg;
        ap_loop_exit_ready_pp0_iter51_reg <= ap_loop_exit_ready_pp0_iter50_reg;
        ap_loop_exit_ready_pp0_iter52_reg <= ap_loop_exit_ready_pp0_iter51_reg;
        ap_loop_exit_ready_pp0_iter53_reg <= ap_loop_exit_ready_pp0_iter52_reg;
        ap_loop_exit_ready_pp0_iter54_reg <= ap_loop_exit_ready_pp0_iter53_reg;
        ap_loop_exit_ready_pp0_iter55_reg <= ap_loop_exit_ready_pp0_iter54_reg;
        ap_loop_exit_ready_pp0_iter56_reg <= ap_loop_exit_ready_pp0_iter55_reg;
        ap_loop_exit_ready_pp0_iter57_reg <= ap_loop_exit_ready_pp0_iter56_reg;
        ap_loop_exit_ready_pp0_iter58_reg <= ap_loop_exit_ready_pp0_iter57_reg;
        ap_loop_exit_ready_pp0_iter59_reg <= ap_loop_exit_ready_pp0_iter58_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter60_reg <= ap_loop_exit_ready_pp0_iter59_reg;
        ap_loop_exit_ready_pp0_iter61_reg <= ap_loop_exit_ready_pp0_iter60_reg;
        ap_loop_exit_ready_pp0_iter62_reg <= ap_loop_exit_ready_pp0_iter61_reg;
        ap_loop_exit_ready_pp0_iter63_reg <= ap_loop_exit_ready_pp0_iter62_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        closepath_reg_1394 <= closepath_fu_439_p2;
        closepath_reg_1394_pp0_iter48_reg <= closepath_reg_1394;
        closepath_reg_1394_pp0_iter49_reg <= closepath_reg_1394_pp0_iter48_reg;
        closepath_reg_1394_pp0_iter50_reg <= closepath_reg_1394_pp0_iter49_reg;
        closepath_reg_1394_pp0_iter51_reg <= closepath_reg_1394_pp0_iter50_reg;
        closepath_reg_1394_pp0_iter52_reg <= closepath_reg_1394_pp0_iter51_reg;
        closepath_reg_1394_pp0_iter53_reg <= closepath_reg_1394_pp0_iter52_reg;
        closepath_reg_1394_pp0_iter54_reg <= closepath_reg_1394_pp0_iter53_reg;
        conv6_reg_1361 <= grp_fu_367_p1;
        conv_reg_1329 <= grp_fu_361_p1;
        din_exp_reg_1381 <= {{data_fu_416_p1[30:23]}};
        din_exp_reg_1381_pp0_iter48_reg <= din_exp_reg_1381;
        din_exp_reg_1381_pp0_iter49_reg <= din_exp_reg_1381_pp0_iter48_reg;
        din_exp_reg_1381_pp0_iter50_reg <= din_exp_reg_1381_pp0_iter49_reg;
        din_exp_reg_1381_pp0_iter51_reg <= din_exp_reg_1381_pp0_iter50_reg;
        din_exp_reg_1381_pp0_iter52_reg <= din_exp_reg_1381_pp0_iter51_reg;
        din_exp_reg_1381_pp0_iter53_reg <= din_exp_reg_1381_pp0_iter52_reg;
        din_exp_reg_1381_pp0_iter54_reg <= din_exp_reg_1381_pp0_iter53_reg;
        din_sig_reg_1388 <= din_sig_fu_435_p1;
        din_sig_reg_1388_pp0_iter48_reg <= din_sig_reg_1388;
        din_sign_reg_1376 <= data_fu_416_p1[32'd31];
        din_sign_reg_1376_pp0_iter48_reg <= din_sign_reg_1376;
        din_sign_reg_1376_pp0_iter49_reg <= din_sign_reg_1376_pp0_iter48_reg;
        din_sign_reg_1376_pp0_iter50_reg <= din_sign_reg_1376_pp0_iter49_reg;
        din_sign_reg_1376_pp0_iter51_reg <= din_sign_reg_1376_pp0_iter50_reg;
        din_sign_reg_1376_pp0_iter52_reg <= din_sign_reg_1376_pp0_iter51_reg;
        din_sign_reg_1376_pp0_iter53_reg <= din_sign_reg_1376_pp0_iter52_reg;
        icmp_ln282_reg_1455 <= icmp_ln282_fu_772_p2;
        icmp_ln282_reg_1455_pp0_iter55_reg <= icmp_ln282_reg_1455;
        icmp_ln282_reg_1455_pp0_iter56_reg <= icmp_ln282_reg_1455_pp0_iter55_reg;
        icmp_ln282_reg_1455_pp0_iter57_reg <= icmp_ln282_reg_1455_pp0_iter56_reg;
        icmp_ln282_reg_1455_pp0_iter58_reg <= icmp_ln282_reg_1455_pp0_iter57_reg;
        icmp_ln282_reg_1455_pp0_iter59_reg <= icmp_ln282_reg_1455_pp0_iter58_reg;
        icmp_ln282_reg_1455_pp0_iter60_reg <= icmp_ln282_reg_1455_pp0_iter59_reg;
        icmp_ln282_reg_1455_pp0_iter61_reg <= icmp_ln282_reg_1455_pp0_iter60_reg;
        icmp_ln282_reg_1455_pp0_iter62_reg <= icmp_ln282_reg_1455_pp0_iter61_reg;
        icmp_ln282_reg_1455_pp0_iter63_reg <= icmp_ln282_reg_1455_pp0_iter62_reg;
        icmp_ln292_reg_1612 <= icmp_ln292_fu_1135_p2;
        icmp_ln306_reg_1618 <= icmp_ln306_fu_1141_p2;
        in_shift_1_reg_1606 <= in_shift_1_fu_1130_p2;
        mul4_reg_1341 <= grp_fu_83_p_dout0;
        mul5_reg_1351 <= grp_fu_353_p2;
        mul7_reg_1366 <= grp_fu_370_p2;
        mul_reg_1346 <= grp_fu_349_p2;
        n_1_reg_1314_pp0_iter10_reg <= n_1_reg_1314_pp0_iter9_reg;
        n_1_reg_1314_pp0_iter11_reg <= n_1_reg_1314_pp0_iter10_reg;
        n_1_reg_1314_pp0_iter12_reg <= n_1_reg_1314_pp0_iter11_reg;
        n_1_reg_1314_pp0_iter13_reg <= n_1_reg_1314_pp0_iter12_reg;
        n_1_reg_1314_pp0_iter14_reg <= n_1_reg_1314_pp0_iter13_reg;
        n_1_reg_1314_pp0_iter15_reg <= n_1_reg_1314_pp0_iter14_reg;
        n_1_reg_1314_pp0_iter16_reg <= n_1_reg_1314_pp0_iter15_reg;
        n_1_reg_1314_pp0_iter17_reg <= n_1_reg_1314_pp0_iter16_reg;
        n_1_reg_1314_pp0_iter18_reg <= n_1_reg_1314_pp0_iter17_reg;
        n_1_reg_1314_pp0_iter19_reg <= n_1_reg_1314_pp0_iter18_reg;
        n_1_reg_1314_pp0_iter20_reg <= n_1_reg_1314_pp0_iter19_reg;
        n_1_reg_1314_pp0_iter21_reg <= n_1_reg_1314_pp0_iter20_reg;
        n_1_reg_1314_pp0_iter22_reg <= n_1_reg_1314_pp0_iter21_reg;
        n_1_reg_1314_pp0_iter23_reg <= n_1_reg_1314_pp0_iter22_reg;
        n_1_reg_1314_pp0_iter24_reg <= n_1_reg_1314_pp0_iter23_reg;
        n_1_reg_1314_pp0_iter25_reg <= n_1_reg_1314_pp0_iter24_reg;
        n_1_reg_1314_pp0_iter26_reg <= n_1_reg_1314_pp0_iter25_reg;
        n_1_reg_1314_pp0_iter27_reg <= n_1_reg_1314_pp0_iter26_reg;
        n_1_reg_1314_pp0_iter28_reg <= n_1_reg_1314_pp0_iter27_reg;
        n_1_reg_1314_pp0_iter29_reg <= n_1_reg_1314_pp0_iter28_reg;
        n_1_reg_1314_pp0_iter2_reg <= n_1_reg_1314_pp0_iter1_reg;
        n_1_reg_1314_pp0_iter30_reg <= n_1_reg_1314_pp0_iter29_reg;
        n_1_reg_1314_pp0_iter31_reg <= n_1_reg_1314_pp0_iter30_reg;
        n_1_reg_1314_pp0_iter32_reg <= n_1_reg_1314_pp0_iter31_reg;
        n_1_reg_1314_pp0_iter33_reg <= n_1_reg_1314_pp0_iter32_reg;
        n_1_reg_1314_pp0_iter34_reg <= n_1_reg_1314_pp0_iter33_reg;
        n_1_reg_1314_pp0_iter35_reg <= n_1_reg_1314_pp0_iter34_reg;
        n_1_reg_1314_pp0_iter36_reg <= n_1_reg_1314_pp0_iter35_reg;
        n_1_reg_1314_pp0_iter37_reg <= n_1_reg_1314_pp0_iter36_reg;
        n_1_reg_1314_pp0_iter38_reg <= n_1_reg_1314_pp0_iter37_reg;
        n_1_reg_1314_pp0_iter39_reg <= n_1_reg_1314_pp0_iter38_reg;
        n_1_reg_1314_pp0_iter3_reg <= n_1_reg_1314_pp0_iter2_reg;
        n_1_reg_1314_pp0_iter40_reg <= n_1_reg_1314_pp0_iter39_reg;
        n_1_reg_1314_pp0_iter41_reg <= n_1_reg_1314_pp0_iter40_reg;
        n_1_reg_1314_pp0_iter42_reg <= n_1_reg_1314_pp0_iter41_reg;
        n_1_reg_1314_pp0_iter43_reg <= n_1_reg_1314_pp0_iter42_reg;
        n_1_reg_1314_pp0_iter44_reg <= n_1_reg_1314_pp0_iter43_reg;
        n_1_reg_1314_pp0_iter45_reg <= n_1_reg_1314_pp0_iter44_reg;
        n_1_reg_1314_pp0_iter46_reg <= n_1_reg_1314_pp0_iter45_reg;
        n_1_reg_1314_pp0_iter47_reg <= n_1_reg_1314_pp0_iter46_reg;
        n_1_reg_1314_pp0_iter48_reg <= n_1_reg_1314_pp0_iter47_reg;
        n_1_reg_1314_pp0_iter49_reg <= n_1_reg_1314_pp0_iter48_reg;
        n_1_reg_1314_pp0_iter4_reg <= n_1_reg_1314_pp0_iter3_reg;
        n_1_reg_1314_pp0_iter50_reg <= n_1_reg_1314_pp0_iter49_reg;
        n_1_reg_1314_pp0_iter51_reg <= n_1_reg_1314_pp0_iter50_reg;
        n_1_reg_1314_pp0_iter52_reg <= n_1_reg_1314_pp0_iter51_reg;
        n_1_reg_1314_pp0_iter53_reg <= n_1_reg_1314_pp0_iter52_reg;
        n_1_reg_1314_pp0_iter54_reg <= n_1_reg_1314_pp0_iter53_reg;
        n_1_reg_1314_pp0_iter55_reg <= n_1_reg_1314_pp0_iter54_reg;
        n_1_reg_1314_pp0_iter56_reg <= n_1_reg_1314_pp0_iter55_reg;
        n_1_reg_1314_pp0_iter57_reg <= n_1_reg_1314_pp0_iter56_reg;
        n_1_reg_1314_pp0_iter58_reg <= n_1_reg_1314_pp0_iter57_reg;
        n_1_reg_1314_pp0_iter59_reg <= n_1_reg_1314_pp0_iter58_reg;
        n_1_reg_1314_pp0_iter5_reg <= n_1_reg_1314_pp0_iter4_reg;
        n_1_reg_1314_pp0_iter60_reg <= n_1_reg_1314_pp0_iter59_reg;
        n_1_reg_1314_pp0_iter61_reg <= n_1_reg_1314_pp0_iter60_reg;
        n_1_reg_1314_pp0_iter62_reg <= n_1_reg_1314_pp0_iter61_reg;
        n_1_reg_1314_pp0_iter63_reg <= n_1_reg_1314_pp0_iter62_reg;
        n_1_reg_1314_pp0_iter6_reg <= n_1_reg_1314_pp0_iter5_reg;
        n_1_reg_1314_pp0_iter7_reg <= n_1_reg_1314_pp0_iter6_reg;
        n_1_reg_1314_pp0_iter8_reg <= n_1_reg_1314_pp0_iter7_reg;
        n_1_reg_1314_pp0_iter9_reg <= n_1_reg_1314_pp0_iter8_reg;
        phase_reg_1371 <= grp_fu_364_p1;
        result_reg_1575 <= {{grp_fu_379_p2[57:29]}};
        results_sign_2_reg_1462 <= results_sign_2_fu_794_p2;
        results_sign_2_reg_1462_pp0_iter55_reg <= results_sign_2_reg_1462;
        results_sign_2_reg_1462_pp0_iter56_reg <= results_sign_2_reg_1462_pp0_iter55_reg;
        results_sign_2_reg_1462_pp0_iter57_reg <= results_sign_2_reg_1462_pp0_iter56_reg;
        results_sign_2_reg_1462_pp0_iter58_reg <= results_sign_2_reg_1462_pp0_iter57_reg;
        results_sign_2_reg_1462_pp0_iter59_reg <= results_sign_2_reg_1462_pp0_iter58_reg;
        results_sign_2_reg_1462_pp0_iter60_reg <= results_sign_2_reg_1462_pp0_iter59_reg;
        results_sign_2_reg_1462_pp0_iter61_reg <= results_sign_2_reg_1462_pp0_iter60_reg;
        results_sign_2_reg_1462_pp0_iter62_reg <= results_sign_2_reg_1462_pp0_iter61_reg;
        results_sign_2_reg_1462_pp0_iter63_reg <= results_sign_2_reg_1462_pp0_iter62_reg;
        second_order_float_sin_cos_K1_load_reg_1540 <= second_order_float_sin_cos_K1_q0;
        second_order_float_sin_cos_K2_load_reg_1545 <= second_order_float_sin_cos_K2_q0;
        sin_basis_reg_1448 <= sin_basis_fu_573_p19;
        sin_basis_reg_1448_pp0_iter55_reg <= sin_basis_reg_1448;
        sin_basis_reg_1448_pp0_iter56_reg <= sin_basis_reg_1448_pp0_iter55_reg;
        sub_ln506_reg_1485 <= sub_ln506_fu_864_p2;
        t1_reg_1535 <= {{second_order_float_sin_cos_K0_q0[29:1]}};
        t1_reg_1535_pp0_iter59_reg <= t1_reg_1535;
        t_reg_1334 <= grp_fu_88_p_dout0;
        t_reg_1334_pp0_iter23_reg <= t_reg_1334;
        t_reg_1334_pp0_iter24_reg <= t_reg_1334_pp0_iter23_reg;
        t_reg_1334_pp0_iter25_reg <= t_reg_1334_pp0_iter24_reg;
        t_reg_1334_pp0_iter26_reg <= t_reg_1334_pp0_iter25_reg;
        tmp_1_i_reg_1580 <= {{grp_fu_379_p2[57:42]}};
        tmp_3_i_reg_1585 <= {{grp_fu_379_p2[41:29]}};
        tmp_7_i_reg_1443 <= {{Mx_bits_3_fu_558_p3[57:29]}};
        tmp_i_reg_1500 <= {{select_ln506_1_fu_894_p3[28:22]}};
        tmp_reg_1479 <= Ex_1_fu_850_p2[32'd7];
        trunc_ln281_1_reg_1600 <= trunc_ln281_1_fu_1126_p1;
        trunc_ln281_reg_1595 <= trunc_ln281_fu_1110_p1;
        trunc_ln2_reg_1550 <= {{mul_ln29_fu_375_p2[44:23]}};
        trunc_ln379_reg_1405 <= trunc_ln379_fu_474_p1;
        trunc_ln3_reg_1555 <= {{mul_ln30_fu_1003_p2[29:16]}};
        trunc_ln5_reg_1590 <= {{grp_fu_379_p2[56:29]}};
        trunc_ln_i_reg_1433 <= {{grp_fu_383_p2[79:77]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        n_1_reg_1314 <= ap_sig_allocacmp_n_1;
        n_1_reg_1314_pp0_iter1_reg <= n_1_reg_1314;
    end
end

always @ (*) begin
    if (((icmp_ln17_fu_401_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter64_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter64 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) 
    & (ap_enable_reg_pp0_iter63 == 1'b0) & (ap_enable_reg_pp0_iter62 == 1'b0) & (ap_enable_reg_pp0_iter61 == 1'b0) & (ap_enable_reg_pp0_iter60 == 1'b0) & (ap_enable_reg_pp0_iter59 == 1'b0) & (ap_enable_reg_pp0_iter58 == 1'b0) & (ap_enable_reg_pp0_iter57 == 1'b0) & (ap_enable_reg_pp0_iter56 == 1'b0) & (ap_enable_reg_pp0_iter55 == 1'b0) & (ap_enable_reg_pp0_iter54 == 1'b0) & (ap_enable_reg_pp0_iter53 == 1'b0) & (ap_enable_reg_pp0_iter52 == 1'b0) & (ap_enable_reg_pp0_iter51 == 1'b0) & (ap_enable_reg_pp0_iter50 == 1'b0) & (ap_enable_reg_pp0_iter49 == 1'b0) & (ap_enable_reg_pp0_iter48 == 1'b0) & (ap_enable_reg_pp0_iter47 == 1'b0) & (ap_enable_reg_pp0_iter46 == 1'b0) & (ap_enable_reg_pp0_iter45 == 1'b0) & (ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 
    == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_n_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_n_1 = n_fu_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter64 == 1'b1))) begin
        out_r_ce0_local = 1'b1;
    end else begin
        out_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter64 == 1'b1))) begin
        out_r_we0_local = 1'b1;
    end else begin
        out_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter47 == 1'b1))) begin
        ref_4oPi_table_100_ce0_local = 1'b1;
    end else begin
        ref_4oPi_table_100_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter57 == 1'b1))) begin
        second_order_float_sin_cos_K0_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter57 == 1'b1))) begin
        second_order_float_sin_cos_K1_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter57 == 1'b1))) begin
        second_order_float_sin_cos_K2_ce0_local = 1'b1;
    end else begin
        second_order_float_sin_cos_K2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign A_fu_937_p3 = {{sin_basis_reg_1448_pp0_iter56_reg}, {tmp_i_reg_1500}};

assign B_fu_901_p1 = select_ln506_1_fu_894_p3[21:0];

assign Ex_1_fu_850_p2 = (select_ln453_fu_805_p3 - trunc_ln505_fu_846_p1);

assign Ex_2_fu_931_p3 = ((sin_basis_reg_1448_pp0_iter56_reg[0:0] == 1'b1) ? Ex_1_reg_1473_pp0_iter56_reg : 8'd0);

assign Ex_fu_800_p2 = ($signed(din_exp_reg_1381_pp0_iter54_reg) + $signed(8'd131));

assign Mx_1_fu_905_p3 = ((sin_basis_reg_1448_pp0_iter55_reg[0:0] == 1'b1) ? Mx_reg_1467 : 29'd536870911);

assign Mx_bits_1_fu_553_p2 = (58'd0 - Mx_bits_reg_1427);

assign Mx_bits_3_fu_558_p3 = ((trunc_ln491_fu_549_p1[0:0] == 1'b1) ? Mx_bits_1_fu_553_p2 : Mx_bits_reg_1427);

assign Mx_zeros_fu_819_p1 = {{tmp_7_i_reg_1443}, {1'd1}};

assign X_fu_495_p3 = {{1'd1}, {din_sig_reg_1388_pp0_iter48_reg}};

assign add_ln300_fu_1178_p2 = ($signed(sext_ln252_fu_1150_p1) + $signed(9'd127));

assign add_ln32_1_fu_1034_p2 = ($signed(add_ln32_fu_1025_p2) + $signed(sext_ln32_2_fu_1031_p1));

assign add_ln32_fu_1025_p2 = ($signed(sext_ln32_fu_1019_p1) + $signed(sext_ln32_1_fu_1022_p1));

assign add_ln376_fu_445_p2 = ($signed(din_exp_fu_427_p3) + $signed(8'd194));

assign addr_fu_451_p3 = ((closepath_fu_439_p2[0:0] == 1'b1) ? 8'd63 : add_ln376_fu_445_p2);

assign and_ln271_fu_517_p2 = (icmp_ln271_fu_507_p2 & icmp_ln271_1_fu_512_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign c_1_fu_1118_p1 = {{tmp_3_i_reg_1585}, {19'd262144}};

assign c_fu_1102_p1 = {{tmp_1_i_reg_1580}, {16'd32768}};

assign closepath_fu_439_p2 = ((din_exp_fu_427_p3 < 8'd126) ? 1'b1 : 1'b0);

assign data_fu_416_p1 = phase_reg_1371;

assign din_exp_fu_427_p3 = {{data_fu_416_p1[30:23]}};

assign din_sig_fu_435_p1 = data_fu_416_p1[22:0];

assign empty_27_fu_1226_p3 = ((icmp_ln292_reg_1612[0:0] == 1'b1) ? tmp_1_fu_1207_p4 : tmp_2_fu_1217_p4);

assign empty_fu_1203_p1 = newexp_fu_1184_p2[7:0];

assign grp_fu_361_p0 = n_1_reg_1314;

assign grp_fu_379_p1 = grp_fu_379_p10;

assign grp_fu_379_p10 = Mx_1_reg_1495_pp0_iter60_reg;

assign grp_fu_383_p1 = grp_fu_383_p10;

assign grp_fu_383_p10 = X_fu_495_p3;

assign grp_fu_77_p_ce = 1'b1;

assign grp_fu_77_p_din0 = mul_reg_1346;

assign grp_fu_77_p_din1 = mul5_reg_1351;

assign grp_fu_77_p_opcode = 2'd0;

assign grp_fu_83_p_ce = 1'b1;

assign grp_fu_83_p_din0 = mul3;

assign grp_fu_83_p_din1 = t_reg_1334;

assign grp_fu_88_p_ce = 1'b1;

assign grp_fu_88_p_din0 = conv_reg_1329;

assign grp_fu_88_p_din1 = fs;

assign icmp_ln17_fu_401_p2 = ((ap_sig_allocacmp_n_1 == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln271_1_fu_512_p2 = ((din_sig_reg_1388_pp0_iter48_reg == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln271_fu_507_p2 = ((din_exp_reg_1381_pp0_iter48_reg == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln282_fu_772_p2 = ((din_exp_reg_1381_pp0_iter53_reg == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln292_fu_1135_p2 = ((trunc_ln281_fu_1110_p1 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln306_fu_1141_p2 = ((result_reg_1575 == 29'd0) ? 1'b1 : 1'b0);

assign in_shift_1_fu_1130_p2 = trunc_ln5_reg_1590 << zext_ln281_fu_1114_p1;

assign in_shift_2_fu_1163_p2 = in_shift_1_reg_1606 << zext_ln281_1_fu_1153_p1;

assign index_fu_613_p3 = {{din_sign_reg_1376_pp0_iter53_reg}, {k_fu_543_p3}};

assign k_fu_543_p3 = ((closepath_reg_1394_pp0_iter53_reg[0:0] == 1'b1) ? 3'd0 : trunc_ln_i_reg_1433);

assign lshr_ln506_fu_882_p2 = zext_ln506_1_fu_879_p1 >> zext_ln506_fu_875_p1;

assign lshr_ln_fu_459_p4 = {{addr_fu_451_p3[7:4]}};

assign mul_ln23_fu_953_p0 = zext_ln23_fu_950_p1;

assign mul_ln23_fu_953_p1 = zext_ln23_fu_950_p1;

assign mul_ln29_fu_375_p1 = mul_ln29_fu_375_p10;

assign mul_ln29_fu_375_p10 = B_reg_1490_pp0_iter58_reg;

assign mul_ln30_fu_1003_p0 = mul_ln30_fu_1003_p00;

assign mul_ln30_fu_1003_p00 = B_squared_reg_1530;

assign n_3_fu_395_p2 = (ap_sig_allocacmp_n_1 + 10'd1);

assign newexp_fu_1184_p2 = (add_ln300_fu_1178_p2 - zext_ln286_fu_1174_p1);

assign not_and_ln271_i_fu_789_p2 = (1'd1 ^ and_ln271_reg_1420_pp0_iter53_reg);

assign or_ln282_fu_1240_p2 = (or_ln306_fu_1198_p2 | icmp_ln282_reg_1455_pp0_iter63_reg);

assign or_ln306_fu_1198_p2 = (tmp_3_fu_1190_p3 | icmp_ln306_reg_1618);

assign out_r_address0 = zext_ln17_fu_1146_p1;

assign out_r_ce0 = out_r_ce0_local;

assign out_r_d0 = t_3_fu_1282_p4;

assign out_r_we0 = out_r_we0_local;

assign ref_4oPi_table_100_address0 = zext_ln378_fu_469_p1;

assign results_exp_1_fu_1268_p3 = ((and_ln271_reg_1420_pp0_iter63_reg[0:0] == 1'b1) ? 8'd127 : results_exp_fu_1245_p3);

assign results_exp_fu_1245_p3 = ((or_ln282_fu_1240_p2[0:0] == 1'b1) ? select_ln282_fu_1233_p3 : empty_fu_1203_p1);

assign results_sig_1_fu_1275_p3 = ((and_ln271_reg_1420_pp0_iter63_reg[0:0] == 1'b1) ? 23'd0 : results_sig_fu_1260_p3);

assign results_sig_fu_1260_p3 = ((or_ln282_fu_1240_p2[0:0] == 1'b1) ? select_ln282_2_fu_1253_p3 : empty_27_fu_1226_p3);

assign results_sign_1_fu_783_p2 = (xor_ln282_fu_777_p2 & results_sign_fu_764_p3);

assign results_sign_2_fu_794_p2 = (results_sign_1_fu_783_p2 & not_and_ln271_i_fu_789_p2);

assign results_sign_fu_764_p3 = ((sin_basis_fu_573_p19[0:0] == 1'b1) ? tmp_4_i_fu_620_p35 : tmp_8_i_fu_692_p35);

assign second_order_float_sin_cos_K0_address0 = zext_ln28_fu_943_p1;

assign second_order_float_sin_cos_K1_address0 = zext_ln28_fu_943_p1;

assign second_order_float_sin_cos_K2_address0 = zext_ln28_fu_943_p1;

assign select_ln282_2_fu_1253_p3 = ((icmp_ln282_reg_1455_pp0_iter63_reg[0:0] == 1'b1) ? 23'd8388607 : 23'd0);

assign select_ln282_fu_1233_p3 = ((icmp_ln282_reg_1455_pp0_iter63_reg[0:0] == 1'b1) ? 8'd255 : 8'd0);

assign select_ln453_fu_805_p3 = ((closepath_reg_1394_pp0_iter54_reg[0:0] == 1'b1) ? Ex_fu_800_p2 : 8'd0);

assign select_ln506_1_fu_894_p3 = ((tmp_reg_1479[0:0] == 1'b1) ? lshr_ln506_fu_882_p2 : shl_ln506_fu_888_p2);

assign select_ln506_fu_870_p3 = ((tmp_reg_1479[0:0] == 1'b1) ? sub_ln506_reg_1485 : Ex_1_reg_1473);

assign sext_ln252_fu_1150_p1 = $signed(Ex_2_reg_1510_pp0_iter63_reg);

assign sext_ln32_1_fu_1022_p1 = $signed(trunc_ln2_reg_1550);

assign sext_ln32_2_fu_1031_p1 = $signed(trunc_ln3_reg_1555);

assign sext_ln32_fu_1019_p1 = $signed(t1_reg_1535_pp0_iter59_reg);

assign shift_1_fu_1156_p3 = {{1'd1}, {trunc_ln281_1_reg_1600}};

assign shift_2_fu_1168_p3 = ((icmp_ln292_reg_1612[0:0] == 1'b1) ? shift_1_fu_1156_p3 : trunc_ln281_reg_1595);

assign shl_ln379_fu_481_p2 = ref_4oPi_table_100_q0 << zext_ln379_fu_478_p1;

assign shl_ln504_fu_831_p2 = Mx_bits_3_reg_1438 << zext_ln504_fu_827_p1;

assign shl_ln506_fu_888_p2 = zext_ln506_1_fu_879_p1 << zext_ln506_fu_875_p1;

assign sin_basis_fu_573_p17 = 'bx;

assign sub_ln506_fu_864_p2 = (8'd0 - Ex_1_fu_850_p2);

assign t_3_fu_1282_p4 = {{{results_sign_2_reg_1462_pp0_iter63_reg}, {results_exp_1_fu_1268_p3}}, {results_sig_1_fu_1275_p3}};

assign tmp_1_fu_1207_p4 = {{in_shift_2_fu_1163_p2[27:5]}};

assign tmp_2_fu_1217_p4 = {{in_shift_1_reg_1606[27:5]}};

assign tmp_3_fu_1190_p3 = newexp_fu_1184_p2[32'd8];

assign tmp_4_i_fu_620_p33 = 'bx;

assign tmp_8_i_fu_692_p33 = 'bx;

assign trunc_ln281_1_fu_1126_p1 = c_1_fu_1118_p3[3:0];

assign trunc_ln281_fu_1110_p1 = c_fu_1102_p3[4:0];

assign trunc_ln379_fu_474_p1 = addr_fu_451_p3[3:0];

assign trunc_ln491_fu_549_p1 = k_fu_543_p3[0:0];

assign trunc_ln505_fu_846_p1 = Mx_zeros_fu_819_p3[7:0];

assign xor_ln282_fu_777_p2 = (icmp_ln282_fu_772_p2 ^ 1'd1);

assign zext_ln17_fu_1146_p1 = n_1_reg_1314_pp0_iter63_reg;

assign zext_ln23_fu_950_p1 = B_trunc_reg_1505_pp0_iter57_reg;

assign zext_ln281_1_fu_1153_p1 = trunc_ln281_1_reg_1600;

assign zext_ln281_fu_1114_p1 = trunc_ln281_fu_1110_p1;

assign zext_ln286_fu_1174_p1 = shift_2_fu_1168_p3;

assign zext_ln28_fu_943_p1 = A_fu_937_p3;

assign zext_ln378_fu_469_p1 = lshr_ln_fu_459_p4;

assign zext_ln379_fu_478_p1 = trunc_ln379_reg_1405;

assign zext_ln504_fu_827_p1 = Mx_zeros_fu_819_p3;

assign zext_ln506_1_fu_879_p1 = Mx_reg_1467;

assign zext_ln506_fu_875_p1 = select_ln506_fu_870_p3;

endmodule //chirp_chirp_Pipeline_VITIS_LOOP_17_1
