-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity chirp is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    out_r_ce0 : OUT STD_LOGIC;
    out_r_we0 : OUT STD_LOGIC;
    out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    fs : IN STD_LOGIC_VECTOR (31 downto 0);
    f0 : IN STD_LOGIC_VECTOR (31 downto 0);
    f1 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of chirp is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "chirp_chirp,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=1126,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3916,HLS_SYN_LUT=5089,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (37 downto 0) := "00000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (37 downto 0) := "00000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (37 downto 0) := "00000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (37 downto 0) := "00000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (37 downto 0) := "00000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (37 downto 0) := "00000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (37 downto 0) := "00000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (37 downto 0) := "00001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (37 downto 0) := "00010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (37 downto 0) := "00100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (37 downto 0) := "01000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (37 downto 0) := "10000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_3F000000 : STD_LOGIC_VECTOR (31 downto 0) := "00111111000000000000000000000000";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_44800000 : STD_LOGIC_VECTOR (31 downto 0) := "01000100100000000000000000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (37 downto 0) := "00000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_88_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal reg_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal ap_CS_fsm_state32 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state32 : signal is "none";
    signal fs_read_reg_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal f0_read_reg_111 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_77_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_reg_117 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_83_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul3_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state36 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state36 : signal is "none";
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_idle : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0 : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0 : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce : STD_LOGIC;
    signal grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state37 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state37 : signal is "none";
    signal ap_CS_fsm_state38 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state38 : signal is "none";
    signal grp_fu_77_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_77_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_83_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_83_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state33 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state33 : signal is "none";
    signal grp_fu_88_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_88_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_fu_77_opcode : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_77_ce : STD_LOGIC;
    signal grp_fu_83_ce : STD_LOGIC;
    signal grp_fu_88_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (37 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ST_fsm_state28_blk : STD_LOGIC;
    signal ap_ST_fsm_state29_blk : STD_LOGIC;
    signal ap_ST_fsm_state30_blk : STD_LOGIC;
    signal ap_ST_fsm_state31_blk : STD_LOGIC;
    signal ap_ST_fsm_state32_blk : STD_LOGIC;
    signal ap_ST_fsm_state33_blk : STD_LOGIC;
    signal ap_ST_fsm_state34_blk : STD_LOGIC;
    signal ap_ST_fsm_state35_blk : STD_LOGIC;
    signal ap_ST_fsm_state36_blk : STD_LOGIC;
    signal ap_ST_fsm_state37_blk : STD_LOGIC;
    signal ap_ST_fsm_state38_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component chirp_chirp_Pipeline_VITIS_LOOP_17_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        fs : IN STD_LOGIC_VECTOR (31 downto 0);
        f0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mul3 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
        out_r_ce0 : OUT STD_LOGIC;
        out_r_we0 : OUT STD_LOGIC;
        out_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_opcode : OUT STD_LOGIC_VECTOR (0 downto 0);
        grp_fu_77_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_77_p_ce : OUT STD_LOGIC;
        grp_fu_83_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_83_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_83_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_83_p_ce : OUT STD_LOGIC;
        grp_fu_88_p_din0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_din1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_dout0 : IN STD_LOGIC_VECTOR (31 downto 0);
        grp_fu_88_p_ce : OUT STD_LOGIC );
    end component;


    component chirp_faddfsub_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        opcode : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component chirp_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component chirp_fdiv_32ns_32ns_32_16_no_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60 : component chirp_chirp_Pipeline_VITIS_LOOP_17_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start,
        ap_done => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done,
        ap_idle => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_idle,
        ap_ready => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready,
        fs => fs_read_reg_100,
        f0 => f0_read_reg_111,
        mul3 => mul3_reg_122,
        out_r_address0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0,
        out_r_ce0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0,
        out_r_we0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0,
        out_r_d0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0,
        grp_fu_77_p_din0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0,
        grp_fu_77_p_din1 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1,
        grp_fu_77_p_opcode => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode,
        grp_fu_77_p_dout0 => grp_fu_77_p2,
        grp_fu_77_p_ce => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce,
        grp_fu_83_p_din0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0,
        grp_fu_83_p_din1 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1,
        grp_fu_83_p_dout0 => grp_fu_83_p2,
        grp_fu_83_p_ce => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce,
        grp_fu_88_p_din0 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0,
        grp_fu_88_p_din1 => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1,
        grp_fu_88_p_dout0 => grp_fu_88_p2,
        grp_fu_88_p_ce => grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce);

    faddfsub_32ns_32ns_32_5_full_dsp_1_U44 : component chirp_faddfsub_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_77_p0,
        din1 => grp_fu_77_p1,
        opcode => grp_fu_77_opcode,
        ce => grp_fu_77_ce,
        dout => grp_fu_77_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U45 : component chirp_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_83_p0,
        din1 => grp_fu_83_p1,
        ce => grp_fu_83_ce,
        dout => grp_fu_83_p2);

    fdiv_32ns_32ns_32_16_no_dsp_1_U46 : component chirp_fdiv_32ns_32ns_32_16_no_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 16,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_88_p0,
        din1 => grp_fu_88_p1,
        ce => grp_fu_88_ce,
        dout => grp_fu_88_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state37)) then 
                    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready = ap_const_logic_1)) then 
                    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                f0_read_reg_111 <= f0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                fs_read_reg_100 <= fs;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state36)) then
                mul3_reg_122 <= grp_fu_83_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state32) or (ap_const_logic_1 = ap_CS_fsm_state16))) then
                reg_94 <= grp_fu_88_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                sub_reg_117 <= grp_fu_77_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done, ap_CS_fsm_state38)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state38) and (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state38;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state32 <= ap_CS_fsm(31);
    ap_CS_fsm_state33 <= ap_CS_fsm(32);
    ap_CS_fsm_state36 <= ap_CS_fsm(35);
    ap_CS_fsm_state37 <= ap_CS_fsm(36);
    ap_CS_fsm_state38 <= ap_CS_fsm(37);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state28_blk <= ap_const_logic_0;
    ap_ST_fsm_state29_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state30_blk <= ap_const_logic_0;
    ap_ST_fsm_state31_blk <= ap_const_logic_0;
    ap_ST_fsm_state32_blk <= ap_const_logic_0;
    ap_ST_fsm_state33_blk <= ap_const_logic_0;
    ap_ST_fsm_state34_blk <= ap_const_logic_0;
    ap_ST_fsm_state35_blk <= ap_const_logic_0;
    ap_ST_fsm_state36_blk <= ap_const_logic_0;
    ap_ST_fsm_state37_blk <= ap_const_logic_0;

    ap_ST_fsm_state38_blk_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done)
    begin
        if ((grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state38_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state38_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) and (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done = ap_const_logic_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done, ap_CS_fsm_state38)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state38) and (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done = ap_const_logic_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg;

    grp_fu_77_ce_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_77_ce <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce;
        else 
            grp_fu_77_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_77_opcode_assign_proc : process(ap_CS_fsm_state12, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_77_opcode <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode),2));
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_77_opcode <= ap_const_lv2_1;
        else 
            grp_fu_77_opcode <= "XX";
        end if; 
    end process;


    grp_fu_77_p0_assign_proc : process(f1, ap_CS_fsm_state12, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_77_p0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_77_p0 <= f1;
        else 
            grp_fu_77_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_77_p1_assign_proc : process(f0, ap_CS_fsm_state12, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_77_p1 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            grp_fu_77_p1 <= f0;
        else 
            grp_fu_77_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_83_ce_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_83_ce <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce;
        else 
            grp_fu_83_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_83_p0_assign_proc : process(reg_94, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0, ap_CS_fsm_state38, ap_CS_fsm_state33)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_83_p0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state33)) then 
            grp_fu_83_p0 <= reg_94;
        else 
            grp_fu_83_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_83_p1_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1, ap_CS_fsm_state38, ap_CS_fsm_state33)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_83_p1 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state33)) then 
            grp_fu_83_p1 <= ap_const_lv32_3F000000;
        else 
            grp_fu_83_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_88_ce_assign_proc : process(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce, ap_CS_fsm_state38)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_88_ce <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce;
        else 
            grp_fu_88_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_88_p0_assign_proc : process(ap_CS_fsm_state1, sub_reg_117, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0, ap_CS_fsm_state38, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_88_p0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            grp_fu_88_p0 <= sub_reg_117;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_88_p0 <= ap_const_lv32_44800000;
        else 
            grp_fu_88_p0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_88_p1_assign_proc : process(ap_CS_fsm_state1, fs, reg_94, grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1, ap_CS_fsm_state38, ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state38)) then 
            grp_fu_88_p1 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            grp_fu_88_p1 <= reg_94;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            grp_fu_88_p1 <= fs;
        else 
            grp_fu_88_p1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    out_r_address0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0;
    out_r_ce0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0;
    out_r_d0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0;
    out_r_we0 <= grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0;
end behav;
