// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="chirp_chirp,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.256000,HLS_SYN_LAT=1126,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3916,HLS_SYN_LUT=5089,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module chirp (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        fs,
        f0,
        f1
);

parameter    ap_ST_fsm_state1 = 38'd1;
parameter    ap_ST_fsm_state2 = 38'd2;
parameter    ap_ST_fsm_state3 = 38'd4;
parameter    ap_ST_fsm_state4 = 38'd8;
parameter    ap_ST_fsm_state5 = 38'd16;
parameter    ap_ST_fsm_state6 = 38'd32;
parameter    ap_ST_fsm_state7 = 38'd64;
parameter    ap_ST_fsm_state8 = 38'd128;
parameter    ap_ST_fsm_state9 = 38'd256;
parameter    ap_ST_fsm_state10 = 38'd512;
parameter    ap_ST_fsm_state11 = 38'd1024;
parameter    ap_ST_fsm_state12 = 38'd2048;
parameter    ap_ST_fsm_state13 = 38'd4096;
parameter    ap_ST_fsm_state14 = 38'd8192;
parameter    ap_ST_fsm_state15 = 38'd16384;
parameter    ap_ST_fsm_state16 = 38'd32768;
parameter    ap_ST_fsm_state17 = 38'd65536;
parameter    ap_ST_fsm_state18 = 38'd131072;
parameter    ap_ST_fsm_state19 = 38'd262144;
parameter    ap_ST_fsm_state20 = 38'd524288;
parameter    ap_ST_fsm_state21 = 38'd1048576;
parameter    ap_ST_fsm_state22 = 38'd2097152;
parameter    ap_ST_fsm_state23 = 38'd4194304;
parameter    ap_ST_fsm_state24 = 38'd8388608;
parameter    ap_ST_fsm_state25 = 38'd16777216;
parameter    ap_ST_fsm_state26 = 38'd33554432;
parameter    ap_ST_fsm_state27 = 38'd67108864;
parameter    ap_ST_fsm_state28 = 38'd134217728;
parameter    ap_ST_fsm_state29 = 38'd268435456;
parameter    ap_ST_fsm_state30 = 38'd536870912;
parameter    ap_ST_fsm_state31 = 38'd1073741824;
parameter    ap_ST_fsm_state32 = 38'd2147483648;
parameter    ap_ST_fsm_state33 = 38'd4294967296;
parameter    ap_ST_fsm_state34 = 38'd8589934592;
parameter    ap_ST_fsm_state35 = 38'd17179869184;
parameter    ap_ST_fsm_state36 = 38'd34359738368;
parameter    ap_ST_fsm_state37 = 38'd68719476736;
parameter    ap_ST_fsm_state38 = 38'd137438953472;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [31:0] out_r_d0;
input  [31:0] fs;
input  [31:0] f0;
input  [31:0] f1;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [37:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_88_p2;
reg   [31:0] reg_94;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state32;
reg   [31:0] fs_read_reg_100;
wire    ap_CS_fsm_state12;
reg   [31:0] f0_read_reg_111;
wire   [31:0] grp_fu_77_p2;
reg   [31:0] sub_reg_117;
wire   [31:0] grp_fu_83_p2;
reg   [31:0] mul3_reg_122;
wire    ap_CS_fsm_state36;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_idle;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready;
wire   [9:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1;
wire   [0:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0;
wire   [31:0] grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1;
wire    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce;
reg    grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state38;
reg   [31:0] grp_fu_77_p0;
reg   [31:0] grp_fu_77_p1;
reg   [31:0] grp_fu_83_p0;
reg   [31:0] grp_fu_83_p1;
wire    ap_CS_fsm_state33;
reg   [31:0] grp_fu_88_p0;
reg   [31:0] grp_fu_88_p1;
wire    ap_CS_fsm_state17;
reg   [1:0] grp_fu_77_opcode;
reg    grp_fu_77_ce;
reg    grp_fu_83_ce;
reg    grp_fu_88_ce;
reg   [37:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
reg    ap_ST_fsm_state38_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 38'd1;
#0 grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg = 1'b0;
end

chirp_chirp_Pipeline_VITIS_LOOP_17_1 grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start),
    .ap_done(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done),
    .ap_idle(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_idle),
    .ap_ready(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready),
    .fs(fs_read_reg_100),
    .f0(f0_read_reg_111),
    .mul3(mul3_reg_122),
    .out_r_address0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0),
    .out_r_ce0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0),
    .out_r_we0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0),
    .out_r_d0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0),
    .grp_fu_77_p_din0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0),
    .grp_fu_77_p_din1(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1),
    .grp_fu_77_p_opcode(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode),
    .grp_fu_77_p_dout0(grp_fu_77_p2),
    .grp_fu_77_p_ce(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce),
    .grp_fu_83_p_din0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0),
    .grp_fu_83_p_din1(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1),
    .grp_fu_83_p_dout0(grp_fu_83_p2),
    .grp_fu_83_p_ce(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce),
    .grp_fu_88_p_din0(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0),
    .grp_fu_88_p_din1(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1),
    .grp_fu_88_p_dout0(grp_fu_88_p2),
    .grp_fu_88_p_ce(grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce)
);

chirp_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_77_p0),
    .din1(grp_fu_77_p1),
    .opcode(grp_fu_77_opcode),
    .ce(grp_fu_77_ce),
    .dout(grp_fu_77_p2)
);

chirp_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_83_p0),
    .din1(grp_fu_83_p1),
    .ce(grp_fu_83_ce),
    .dout(grp_fu_83_p2)
);

chirp_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_88_p0),
    .din1(grp_fu_88_p1),
    .ce(grp_fu_88_ce),
    .dout(grp_fu_88_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state37)) begin
            grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_ready == 1'b1)) begin
            grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        f0_read_reg_111 <= f0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        fs_read_reg_100 <= fs;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        mul3_reg_122 <= grp_fu_83_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_94 <= grp_fu_88_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        sub_reg_117 <= grp_fu_77_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

always @ (*) begin
    if ((grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done == 1'b0)) begin
        ap_ST_fsm_state38_blk = 1'b1;
    end else begin
        ap_ST_fsm_state38_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) & (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state38) & (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_77_ce = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_ce;
    end else begin
        grp_fu_77_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_77_opcode = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_77_opcode = 2'd1;
    end else begin
        grp_fu_77_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_77_p0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_77_p0 = f1;
    end else begin
        grp_fu_77_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_77_p1 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_77_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_77_p1 = f0;
    end else begin
        grp_fu_77_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_83_ce = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_ce;
    end else begin
        grp_fu_83_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_83_p0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_83_p0 = reg_94;
    end else begin
        grp_fu_83_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_83_p1 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_83_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state33)) begin
        grp_fu_83_p1 = 32'd1056964608;
    end else begin
        grp_fu_83_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_88_ce = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_ce;
    end else begin
        grp_fu_88_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_88_p0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_88_p0 = sub_reg_117;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_88_p0 = 32'd1149239296;
    end else begin
        grp_fu_88_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_fu_88_p1 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_grp_fu_88_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_88_p1 = reg_94;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_88_p1 = fs;
    end else begin
        grp_fu_88_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((1'b1 == ap_CS_fsm_state38) & (grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_ap_start_reg;

assign out_r_address0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_address0;

assign out_r_ce0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_ce0;

assign out_r_d0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_d0;

assign out_r_we0 = grp_chirp_Pipeline_VITIS_LOOP_17_1_fu_60_out_r_we0;

endmodule //chirp
