# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip/chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip || ORIG_REF_NAME==chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip/chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip/chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip || ORIG_REF_NAME==chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip/chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fpext_32ns_64_2_no_dsp_1_ip/chirp_fpext_32ns_64_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==chirp_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fptrunc_64ns_32_2_no_dsp_1_ip/chirp_fptrunc_64ns_32_2_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==chirp_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_sitofp_32ns_32_6_no_dsp_1_ip/chirp_sitofp_32ns_32_6_no_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_sitofp_32ns_32_6_no_dsp_1_ip || ORIG_REF_NAME==chirp_sitofp_32ns_32_6_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/chirp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip/chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip || ORIG_REF_NAME==chirp_dmul_64ns_64ns_64_7_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip/chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==chirp_faddfsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip/chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip || ORIG_REF_NAME==chirp_fdiv_32ns_32ns_32_16_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip/chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==chirp_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fpext_32ns_64_2_no_dsp_1_ip/chirp_fpext_32ns_64_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fpext_32ns_64_2_no_dsp_1_ip || ORIG_REF_NAME==chirp_fpext_32ns_64_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_fptrunc_64ns_32_2_no_dsp_1_ip/chirp_fptrunc_64ns_32_2_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_fptrunc_64ns_32_2_no_dsp_1_ip || ORIG_REF_NAME==chirp_fptrunc_64ns_32_2_no_dsp_1_ip} -quiet] -quiet

# IP: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/chirp_sitofp_32ns_32_6_no_dsp_1_ip/chirp_sitofp_32ns_32_6_no_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==chirp_sitofp_32ns_32_6_no_dsp_1_ip || ORIG_REF_NAME==chirp_sitofp_32ns_32_6_no_dsp_1_ip} -quiet] -quiet

# XDC: c:/Users/vempa/Documents/Projects/RADAR_Chirp_Engine/ChirpGenerator/ChirpGenerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/chirp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
